---
logging:
  format: "%(asctime)s %(levelname)s >> %(message)s"
  level: INFO
  file_logging: True

grouper:
  dbscan_min_samples: 1
  dbscan_eps: 1.1
  freq_scale: 0.5
  dm_scale: 0.1
  ra_scale: 0.2
  dec_scale: 0.2
  metric: "chebyshev"

harmonic_clusterer:
  dbscan_min_samples: 1
  neighborhood_max_dist: 1.1
  max_harm: 64
  dm_scale: 0.1
  ra_scale: 0.5
  dec_scale: 1
  neighborhood_metric: "chebyshev"
  frac_eps: 0.01

sifter:
  threshold: 0.997
  ks_filters:
    - ["compare_position", 1.0]
    - ["compare_dm", 2.0]
    - ["compare_frequency", 4.0]
  rfi_check:
    delta_freq:
      threshold: 0.003
      operator: gt # should exist in operator module
    num_candidates:
      threshold: 200
      operator: gt # gt meaning values larger than threshold will be ignored by the ks sifter
    best_harmonic_sum:
      threshold: 2
      operator: lt

classifier:
  active_classifiers:
    # a class in sps_multi_pointing.classifier.classifier:
    - DummyClassifier
    #
    # alternatively, a fully-qualified class name:
    # - sps_multi_pointing.classifier.classifier.DummyClassifier
    #
    # if needing constructor arguments, use a dictionary:
    # - SvmClassifier:
    #     classifier_file: MODEL_FILE_NAME
