name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  # GitHub Actions fails if any "with" parameter is empty when using reusable workflows, so needs || fallbacks
  check-release:
    uses: ./.github/workflows/release.yml
    secrets: inherit
  latest-image:
    needs: check-release
    if: ${{ !needs.check-release.outputs.release_created }}
    uses: ./.github/workflows/image.yml
    secrets: inherit
    with:
      image_tag: 'latest'
      build_locally: false
  version-image:
    needs: check-release
    if: ${{ needs.check-release.outputs.release_created == 'true' }}
    uses: ./.github/workflows/image.yml
    secrets: inherit
    with:
      # E.g. v1.0.0, only set if merging automated release PR
      image_tag: ${{ needs.check-release.outputs.release_tag || 'none' }}
      build_locally: false


  # === Singularity images (on your self-hosted runner) ===

  # Build "latest" Singularity image from DockerHub
  singularity-latest:
    needs: latest-image
    runs-on: [self-hosted, sps-compute2]
    steps:
      - name: Build latest Singularity image
        run: |
          /usr/bin/apptainer build /data/chime/sps/apptainer/champss_software.sif \
            docker://chimefrb/champss_software:latest

  # Build a release-tagged Singularity image from DockerHub
  singularity-release:
    needs: version-image
    if: ${{ needs.check-release.outputs.release_created == 'true' }}
    runs-on: self-hosted
    steps:
      - name: Build release-tagged Singularity image
        run: |
          apptainer build /data/chime/sps/apptainer/champss_${{ needs.check-release.outputs.release_tag }}.sif \
            docker://chimefrb/champss_software:${{ needs.check-release.outputs.release_tag }}

