name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  # Commenting this out as all Precommit checks are now done locally and have been automated as much as possible
  # precommit:
  #   Avoid double checks from bot's automated release PR
  #   if: ${{ github.actor != 'github-actions' && github.event_name == 'pull_request' }}
  #   uses: ./.github/workflows/precommit.yml
  #   secrets: inherit
  benchmark:
    if: ${{ github.actor != 'github-actions' && (github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch') }}
    uses: ./.github/workflows/benchmark.yml
    secrets: inherit
    with:
      branch_name: ${{ github.head_ref || 'benchmark' }}
  test:
    # Last check makes sure we're not building a test image if pushing to main, as that will already trigger a build in continuous-deployment.yml
    if: ${{ github.actor != 'github-actions' && (contains(github.event.head_commit.message, '[test]') == true) && github.event_name == 'push' && github.ref_name != 'main' }}
    uses: ./.github/workflows/image.yml
    secrets: inherit
    with:
      runs_on: 'sps-compute3'
      image_tag: ${{ github.ref_name || 'test' }}
      build_locally: false
